services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_teste
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPass123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/init.sql
      - ./task1.sql:/task1.sql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'MyStrongPass123!' -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5
