version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_teste
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPass123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./teste1/init.sql:/docker-entrypoint-initdb.d/init.sql
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql_network

volumes:
  sqlserver_data:

networks:
  sql_network:
    driver: bridge
